<a href="https://colab.research.google.com/github/rajlaxmiac/LogicMojo-AI-ML-April26-RajlaxmiSingh/blob/My-learning-Journey/Linear.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import warnings
warnings.filterwarnings('ignore')

In [ ]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
df = pd.read_csv('/content/drive/MyDrive/Housing - Housing.csv.csv')
df.head()

,price,area,bedrooms,bathrooms,stories,mainroad,guestroom,basement,hotwaterheating,airconditioning,parking,prefarea,furnishingstatus
0,13300000,7420,4,2,3,yes,no,no,no,yes,2,yes,furnished
1,12250000,8960,4,4,4,yes,no,no,no,yes,3,no,furnished
2,12250000,9960,3,2,2,yes,no,yes,no,no,2,yes,semi-furnished
3,12215000,7500,4,2,2,yes,no,yes,no,yes,3,yes,furnished
4,11410000,7420,4,1,2,yes,yes,yes,no,yes,2,no,furnished

In [ ]:
df['furnishingstatus'].value_counts()

furnishingstatus
semi-furnished    227
unfurnished       178
furnished         140
Name: count, dtype: int64

In [ ]:
df.head()

,price,area,bedrooms,bathrooms,stories,mainroad,guestroom,basement,hotwaterheating,airconditioning,parking,prefarea,furnishingstatus
0,13300000,7420,4,2,3,yes,no,no,no,yes,2,yes,furnished
1,12250000,8960,4,4,4,yes,no,no,no,yes,3,no,furnished
2,12250000,9960,3,2,2,yes,no,yes,no,no,2,yes,semi-furnished
3,12215000,7500,4,2,2,yes,no,yes,no,yes,3,yes,furnished
4,11410000,7420,4,1,2,yes,yes,yes,no,yes,2,no,furnished

In [ ]:
categorical = ['mainroad', 'guestroom', 'basement', 'hotwaterheating', 'airconditioning', 'prefarea', 'furnishingstatus']

#binary = ['']
df[categorical].head()

def binary_map(x):
  return x.map({'yes': 1, 'no': 0})
binary = ['mainroad', 'guestroom', 'basement', 'hotwaterheating', 'airconditioning', 'prefarea']

for col in binary:
    df[col] = df[col].map({'yes': 1, 'no': 0})

df[binary].head()

   mainroad  guestroom  basement  hotwaterheating  airconditioning  prefarea
0         1          0         0                0                1         1
1         1          0         0                0                1         0
2         1          0         1                0                0         1
3         1          0         1                0                1         1
4         1          1         1                0                1         0

In [ ]:
status = pd.get_dummies(df['furnishingstatus'], drop_first=True)

In [ ]:
df.drop('furnishingstatus', axis=1, inplace=True)

In [15]:
### train test split
from sklearn.model_selection import train_test_split

df_train, df_test = train_test_split(df, train_size=0.8, random_state=101)
df_train.shape
df_test.shape

(109, 12)

In [16]:
df_train.shape

(436, 12)

In [18]:
from sklearn.preprocessing import MinMaxScaler

scaler = MinMaxScaler()

In [20]:
y_train = df_train['price']
x_train = df_train.drop('price', axis=1)

x_train = x_train.apply(pd.to_numeric, errors='coerce')
x_train.info()

<class 'pandas.core.frame.DataFrame'>
Index: 436 entries, 430 to 523
Data columns (total 11 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   area             436 non-null    int64
 1   bedrooms         436 non-null    int64
 2   bathrooms        436 non-null    int64
 3   stories          436 non-null    int64
 4   mainroad         436 non-null    int64
 5   guestroom        436 non-null    int64
 6   basement         436 non-null    int64
 7   hotwaterheating  436 non-null    int64
 8   airconditioning  436 non-null    int64
 9   parking          436 non-null    int64
 10  prefarea         436 non-null    int64
dtypes: int64(11)
memory usage: 40.9 KB

In [22]:
import statsmodels.api as sm
x_train = sm.add_constant(x_train)

In [24]:
lr = sm.OLS(y_train, x_train).fit()